apiVersion: v1
kind: Service
metadata:
  labels:
    app: songs-service
  name: songs-postgresql
spec:
  ports:
    - name: tcp-5432
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: songs-postgresql
