apiVersion: apps/v1
kind: Deployment
metadata:
  name: albums-service
spec:
  template:
    spec:
      containers:
        - name: albums-service
          image: example.org/right-lyrics/albums-service:latest
