apiVersion: v1
kind: Service
metadata:
  labels:
    app: lyrics-page
  name: lyrics-page
  namespace: {{ meta.namespace }}
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: lyrics-page