apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: rl-hits-service
  name: rl-hits-service
  namespace: {{ meta.namespace }}
spec:
  replicas: {Â hits_service_replicas }
  selector:
    app: rl-hits-service
    deploymentconfig: rl-hits-service
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: rl-hits-service
        deploymentconfig: rl-hits-service
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: rl-hits-redis
        - name: DB_PASSWORD
          value: right-lyrics
        image: ''
        name: rl-hits-service
        ports:
        - containerPort: 8080
          protocol: TCP
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - rl-hits-service
      from:
        kind: ImageStreamTag
        name: rl-hits-service:latest
        namespace: right-lyrics
    type: ImageChange