apiVersion: apps/v1
kind: Deployment
metadata:
  name: albums-service
spec:
  template:
    spec:
      containers:
        - name: albums-service
          image: image-registry.openshift-image-registry.svc:5000/right-lyrics/albums-service:latest
 