bases:
  - ../../base
patchesStrategicMerge:
  - resources-patch.yaml
  - image-patch.yaml
secretGenerator:
  - name: albums-mariadb
    literals:
      - user=rl
      - password=rl
      - database=rl
