bases:
  - ../../base
patchesStrategicMerge:
  - resources-patch.yaml
secretGenerator:
  - name: songs-postgresql
    literals:
      - user=right-lyrics
      - password=right-lyrics
      - database=right-lyrics