apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: lyrics  
spec:
  rules:
    - host: right.lyrics
      http:
        paths:
          - path: /api/lyric
            backend:
              serviceName: lyrics-service
              servicePort: 8080
