apiVersion: v1
kind: Service
metadata:
  labels:
    app: hits-service
  name: hits-redis
spec:
  ports:
    - name: tcp-6379
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: hits-redis
